name: maas
version: git
version-script: utilities/calc-snap-version
summary: Metal as a Service
description: |
  Total automation of your physical servers for amazing data center operational efficiency.
grade: stable
confinement: strict

apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
  maas:
    command: bin/maas

parts:
  distro-info:
    plugin: nil
    stage-packages:
      - python3-distro-info
    stage:
      - usr/share/distro-info/debian.csv
      - usr/share/distro-info/ubuntu.csv
  packages:
    plugin: nil
    stage-packages:
      - archdetect-deb
      - avahi-utils
      - bind9
      - gpgv
      - iproute2
      - isc-dhcp-client
      - isc-dhcp-server
      - libconfig-general-perl
      - libjs-angularjs
      - libjs-jquery
      - libjs-yui3-full
      - libjs-yui3-min
      - lshw
      - ntp
      - openssh-client
      - postgresql
      - squid
      - tcpdump
      - tgt
      - ubuntu-cloudimage-keyring
    install: |
      ln -s ../usr/lib/postgresql/9.5/bin/initdb $SNAPCRAFT_PART_INSTALL/bin/initdb
      ln -s ../usr/lib/postgresql/9.5/bin/pg_ctl $SNAPCRAFT_PART_INSTALL/bin/pg_ctl
      ln -s ../usr/lib/postgresql/9.5/bin/postgres $SNAPCRAFT_PART_INSTALL/bin/postgres
      ln -s ../usr/lib/postgresql/9.5/bin/psql $SNAPCRAFT_PART_INSTALL/bin/psql
  power-drivers:
    plugin: nil
    stage-packages:
      - amtterm        # AMT
      - libsoap-lite-perl # Missing dependencies for AMT
      - libxml-parser-perl # Missing dependencies for AMT
      - libxml-parser-lite-perl # Missing dependencies for AMT
      - wsmancli       # AMT
      - snmp           # APC
      - wget           # DLI
      - fence-agents   # Fence CDU
      - freeipmi-tools # IPMI
      - ipmitool       # Moonshot
      - libvirt-bin    # Virsh
    filesets:
      remove:
        - -lib/systemd
    stage:
      - $remove
    prime:
      - $remove
  maas:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - build-essential
      - bzr
      - git
      - libffi-dev
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
    stage-packages:
      - python3-bson
      - python3-convoy
      - python3-crochet
      - python3-django
      - python3-django-piston3
      - python3-djorm-ext-pgarray
      - python3-distro-info
      - python3-formencode
      - python3-httplib2
      - python3-jsonschema
      - python3-lxml
      - python3-netaddr
      - python3-netifaces
      - python3-paramiko
      - python3-petname
      - python3-pexpect
      - python3-psycopg2
      - python3-pyparsing
      - python3-requests
      - python3-sphinx
      - python3-tempita
      - python3-twisted
      - python3-zope.interface
      - python3-seamicroclient
      - python3-txtftp
      - python3-yaml
      - python3-simplestreams
      - python3-curtin
      - python3-oauth
      - python3-oauthlib
      - python3-attr
      - python3-simplejson
      - python3-markupsafe
    organize:
        lib/python3.*/site-packages/etc/*: etc
        lib/python3.*/site-packages/usr/bin/*: usr/bin
        lib/python3.*/site-packages/usr/lib/*: usr/lib
        lib/python3.*/site-packages/usr/sbin/*: usr/sbin
        lib/python3.*/site-packages/usr/share/*: usr/share
        usr/lib/curtin/helpers: usr/lib/python3/dist-packages/helpers
    filesets:
      remove:
        - -lib/python3.*/site-packages/etc
        - -lib/python3.*/site-packages/usr
        - -lib/python3/dist-packages/maastesting
        - -share
        - -usr/include/libjs-angularjs
        - -usr/share/applications
        - -usr/share/bug
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/perl5
        - -var/lib/ieee-data/oui36.txt
        - -var/lib/ieee-data/mam.txt
    stage:
      - $remove
    prime:
      - $remove
  region-static:
    plugin: dump
    source: src/maasserver/static
    organize:
      '*': usr/share/maas/web/static/
  twisted-plugins:
    plugin: dump
    source: twisted/plugins
    organize:
      maasrackd.py: usr/lib/python3/dist-packages/twisted/plugins/maasrackd.py
      maasregiond.py: usr/lib/python3/dist-packages/twisted/plugins/maasregiond.py
  snap:
    plugin: dump
    source: snap
    organize:
      bind: usr/share/maas/bind
      conf/empty.tgt: usr/share/maas/empty.tgt
      conf/ntp.conf: usr/share/maas/ntp.conf
      conf/supervisord.conf.template: usr/share/maas/supervisord.conf.template
    stage:
      - -conf
      - -plugins
      - -snapcraft.yaml
    prime:
      - -conf
      - -plugins
      - -snapcraft.yaml
