name: maas
version: trunk
summary: Metal as a Service
description: |
  Total automation of you physical servers for amazing data center
  operational efficiency.
grade: devel
confinement: devmode

apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
  maas:
    command: bin/maas

parts:
  distro-info:
    plugin: nil
    stage-packages:
      - python3-distro-info
    organize:
      usr/lib/python3/dist-packages/distro_info.py: lib/python3.5/site-packages/distro_info.py
    stage:
      - lib/python3.5/site-packages/distro_info.py
      - usr/share/distro-info/debian.csv
      - usr/share/distro-info/ubuntu.csv
  packages:
    plugin: nil
    stage-packages:
      - archdetect-deb
      - avahi-utils
      - bind9
      - gpgv
      - iproute2
      - isc-dhcp-client
      - isc-dhcp-server
      - libconfig-general-perl
      - libjs-angularjs
      - libjs-jquery
      - libjs-yui3-full
      - libjs-yui3-min
      - lshw
      - ntp
      - openssh-client
      - postgresql
      - squid
      - tcpdump
      - tgt
      - ubuntu-cloudimage-keyring
    install: |
      ln -s ../usr/lib/postgresql/9.5/bin/initdb $SNAPCRAFT_PART_INSTALL/bin/initdb
      ln -s ../usr/lib/postgresql/9.5/bin/pg_ctl $SNAPCRAFT_PART_INSTALL/bin/pg_ctl
      ln -s ../usr/lib/postgresql/9.5/bin/postgres $SNAPCRAFT_PART_INSTALL/bin/postgres
      ln -s ../usr/lib/postgresql/9.5/bin/psql $SNAPCRAFT_PART_INSTALL/bin/psql
  power-drivers:
    plugin: nil
    stage-packages:
      - amtterm        # AMT
      - wsmancli       # AMT
      - snmp           # APC
      - wget           # DLI
      - fence-agents   # Fence CDU
      - freeipmi-tools # IPMI
      - ipmitool       # Moonshot
      - libvirt-bin    # Virsh
    filesets:
      remove:
        - -lib/systemd
    stage:
      - $remove
    prime:
      - $remove
  maas:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - build-essential
      - bzr
      - git
      - libffi-dev
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
    filesets:
      remove:
        - -lib/python3.5/site-packages/maastesting
        - -share
        - -usr/include/libjs-angularjs
        - -usr/share/applications
        - -usr/share/bug
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/perl5
    organize:
      lib/python3.5/site-packages/etc: etc
      lib/python3.5/site-packages/usr: usr
      usr/lib/curtin/helpers: lib/python3.5/site-packages/helpers
    stage:
      - $remove
    prime:
      - $remove
  region-static:
    plugin: dump
    source: src/maasserver/static
    organize:
      '*': usr/share/maas/web/static/
  twisted-plugins:
    plugin: dump
    source: twisted/plugins
    organize:
      maasrackd.py: lib/python3.5/site-packages/twisted/plugins/maasrackd.py
      maasregiond.py: lib/python3.5/site-packages/twisted/plugins/maasregiond.py
  snap:
    plugin: dump
    source: snap
    organize:
      bind: usr/share/maas/bind
      conf/empty.tgt: usr/share/maas/empty.tgt
      conf/ntp.conf: usr/share/maas/ntp.conf
      conf/supervisord.conf.template: usr/share/maas/supervisord.conf.template
    stage:
      - -conf
      - -plugins
      - -snapcraft.yaml
    prime:
      - -conf
      - -plugins
      - -snapcraft.yaml
  version:
    plugin: bzr-version
    stage:
      - -*
    prime:
      - -*
