name: maas
version: git
version-script: utilities/calc-snap-version
summary: Metal as a Service
description: |
  Total automation of your physical servers for amazing data center operational efficiency.
grade: stable
confinement: strict
base: core18

apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
  maas:
    command: bin/maas

parts:
  maas:
    plugin: python
    source: .
    requirements: requirements.txt
    build-attributes: [no-system-libraries]
    build-packages:
      - build-essential
      - bzr
      - git
      - libffi-dev
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
    stage-packages:
      - amtterm                 # AMT
      - libsoap-lite-perl       # Dependencies for AMT
      - libxml-parser-perl      # Dependencies for AMT
      - libxml-parser-lite-perl # Dependencies for AMT
      - wsmancli                # AMT
      - snmp                    # APC
      - wget                    # DLI
      - fence-agents            # Fence CDU
      - freeipmi-tools          # IPMI
      - ipmitool                # Moonshot
      - libvirt-clients         # Virsh
      - archdetect-deb
      - avahi-utils
      - bind9
      - gpgv
      - iproute2
      - isc-dhcp-client
      - isc-dhcp-server
      - libjs-angularjs
      - libjs-jquery
      - lshw
      - chrony
      - openssh-client
      - postgresql
      - python3-bson
      - python3-convoy
      - python3-crochet
      - python3-django
      - python3-django-piston3
      - python3-djorm-ext-pgarray
      - python3-distro-info
      - python3-formencode
      - python3-httplib2
      - python3-jsonschema
      - python3-lxml
      - python3-macaroonbakery
      - python3-netaddr
      - python3-netifaces
      - python3-paramiko
      - python3-petname
      - python3-pexpect
      - python3-psycopg2
      - python3-pyparsing
      - python3-requests
      - python3-sphinx
      - python3-tempita
      - python3-twisted
      - python3-zope.interface
      - python3-seamicroclient
      - python3-txtftp
      - python3-yaml
      - python3-simplestreams
      - python3-curtin
      - python3-oauth
      - python3-oauthlib
      - python3-attr
      - python3-simplejson
      - python3-markupsafe
      - squid
      - tcpdump
      - ubuntu-keyring
    organize:
        lib/python3.*/site-packages/etc/*: etc
        lib/python3.*/site-packages/usr/bin/*: usr/bin
        lib/python3.*/site-packages/usr/lib/*: usr/lib
        lib/python3.*/site-packages/usr/sbin/*: usr/sbin
        lib/python3.*/site-packages/usr/share/*: usr/share
        usr/lib/curtin/helpers: usr/lib/python3/dist-packages/helpers
    filesets:
      remove:
        - -lib/python3.*/site-packages/etc
        - -lib/python3.*/site-packages/usr
        - -lib/python3/dist-packages/maastesting
        - -share
        - -usr/bin/xdg-*
        - -usr/include/libjs-angularjs
        - -usr/share/applications
        - -usr/share/bug
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/doc
        - -usr/share/doc-base
        - -usr/share/lintian
        - -usr/share/man
        - -usr/share/perl5
        - -var/lib/ieee-data/oui36.txt
        - -var/lib/ieee-data/mam.txt
    stage:
      - $remove
    prime:
      - $remove
    override-build: |
      snapcraftctl build
      ln -s ../usr/lib/postgresql/10/bin/initdb $SNAPCRAFT_PART_INSTALL/bin/initdb
      ln -s ../usr/lib/postgresql/10/bin/pg_ctl $SNAPCRAFT_PART_INSTALL/bin/pg_ctl
      ln -s ../usr/lib/postgresql/10/bin/postgres $SNAPCRAFT_PART_INSTALL/bin/postgres
      ln -s ../usr/lib/postgresql/10/bin/psql $SNAPCRAFT_PART_INSTALL/bin/psql
      # If python3-netaddr contains absolute symlinks.
      # See https://bugs.launchpad.net/snapcraft/+bug/1774410
      ln -s -f ../../../../../../var/lib/ieee-data/oui.txt $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/oui.txt
      ln -s -f ../../../../../../var/lib/ieee-data/iab.txt $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages/netaddr/eui/iab.txt
  region-static:
    plugin: dump
    source: src/maasserver/static
    organize:
      '*': usr/share/maas/web/static/
  snap:
    plugin: dump
    source: snap
    organize:
      bind: usr/share/maas/bind
      conf/chrony.conf: usr/share/maas/chrony.conf
      conf/supervisord.conf.template: usr/share/maas/supervisord.conf.template
    stage:
      - -conf
      - -plugins
      - -snapcraft.yaml
    prime:
      - -conf
      - -plugins
      - -snapcraft.yaml
